### ISSUE TITLE
Please fix typos

### ISSUE THREAD

**Issue by ayu-exorcist** [krausest/krausest.github.io#2]
[typo: 2024 -> 2023]

[typo: 2024 -> 2023]: https://github.com/krausest/krausest.github.io/blob/master/js-framework-benchmark/index.html#L49-L64

![image](https://github.com/krausest/krausest.github.io/assets/54145886/251ef2ad-73dd-4cd2-91f9-893986d48909)

**Comment by krausest** [comment]
Fixed - thanks!
